### ISSUE TITLE
verb taxonomies

### ISSUE THREAD

**Issue by cruncher64** [msg-systems/holmes-extractor#10]
I am using holmes extractor with ontology-based matching and it is working fine for taxonomies of nouns (or instances of these), even for compund nouns.
The same is not working for verbs: if we have a verb like 'move' and a subclass of it like 'walk' in the ontology, then 'walk' is not recognized (if 'move' is used in the search phrase), only synonyms (owl:equivalentClass) are working.
So my questions are: 

- is this the correct function or am I doing something wrong?

- and if the function is missing, are there plans to extend the taxonomy support also for verbs?

Thank you in advance.

**Comment by richardpaulhudson** [comment]
Hi @cruncher64, the design of Holmes does not differentiate between nouns and verbs within ontologies: the relationship between the two verbs in the example you give should be treated in the same way as a relationship between two nouns, and indeed this test works where 'walk' is defined as a subclass as 'move' in the ontology:

```
import holmes_extractor as holmes
ontology = holmes.Ontology('ontology.owl')
manager = holmes.Manager('en_core_web_trf', ontology=ontology)
manager.register_search_phrase("An ENTITYPERSON moves")
manager.parse_and_register_document("Richard Hudson walked")
manager.match()
```

Perhaps there is a problem either with how one of the sentences is being parsed or with the ontology definition?
