### ISSUE TITLE
Chatbot mode register_search_phrase has to be a full sentence?

### ISSUE THREAD

**Issue by zhoudoufu** [msg-systems/holmes-extractor#2]
Hi, @richardpaulhudson 
I have tested this tool with code
```python
import holmes_extractor as holmes
holmes_manager = holmes.Manager(model='en_core_web_lg')
holmes_manager.register_search_phrase('be all ear')
holmes_manager.start_chatbot_mode_console()
```
I am trying to do "phrase" search, and found out that, once the sentence contains a "be" verb, this will lead to detection of "be all ear".
I suppose this search phrase should be a full sentence, a phrase like stuff is not supported when you saying Ungrammatical expressions.  (Cause I found it a little bit misleading of search phrase and search "phrase")

**Comment by richardpaulhudson** [comment]
Hi @zhoudoufu, search phrases do not need to be a full sentence but should be grammatically correct. For some reason, spaCy does not parse 'ear' as a noun in the phrase 'be all ear' so the search phrase does not work. However, the correct idiom is actually 'be all ear**s**', which works as expected.
