### ISSUE TITLE
[Question] Further references?

### ISSUE THREAD

**Issue by ezorita** [msg-systems/holmes-extractor#4]
@richardpaulhudson thanks for this precious contribution to the open source community, not only the library itself but the documentation and NLP insights are awesome. I was wondering if you would have any scientific literature suggestion about the following topics:
- searching over large corpora similar to what you do in the holmes demo https://holmes-demo.xt.msg.team/
- using a similar nlp-processing logic to build knowledge graphs from unstructured text

Many thanks again!

**Comment by richardpaulhudson** [comment]
Hi @ezorita, I am glad you are finding Holmes useful! 

- I am currently preparing a scientific paper that addresses the first of these two topics and will let you know when it has been published. 

- The second topic seems to be a frequent requirement in a variety of projects. While it could certainly be facilitated using structural extraction with Holmes, it is not within the main focus of the library. Please let us know if you find any other open-source resources that implement it.

Best wishes from Munich,

Richard
