### ISSUE TITLE
Language support for Spanish?

### ISSUE THREAD

**Issue by Joepetey** [msg-systems/holmes-extractor#7]
Any plans to add Spanish as a language, or any ideas how I could get this to work for spanish?

**Comment by richardpaulhudson** [comment]
Hi @Joepetey, I don't have any firm plans to add Spanish at present although it is something I've thought about doing at some undefined point in the future. If you decided to do so now, that would be great and I could definitely help you along the way.

At the moment English and German are supported. The code and data specific to each language is located in the two subdirectories of [https://github.com/msg-systems/holmes-extractor/tree/master/holmes_extractor/lang](https://github.com/msg-systems/holmes-extractor/tree/master/holmes_extractor/lang), and the corresponding tests are located in subdirectories of [https://github.com/msg-systems/holmes-extractor/tree/master/tests](https://github.com/msg-systems/holmes-extractor/tree/master/tests). The way to approach adding Spanish support would be to go through the English rules and tests, looking at what each method in the English rules class is doing, trying out equivalent sentences with the `es_core_news_lg` spaCy model and adding Spanish equivalents. Some bits like the phraselet template definitions may be hard to grasp, but I could do these bits myself. Let me know if you decide to proceed with this!

Best wishes, Richard
