### ISSUE TITLE
Ubuntu Installation problem

### ISSUE THREAD

**Issue by sdspieg** [msg-systems/holmes-extractor#9]
Trying to install this in Ubuntu 22.04, I get these types of errors. Any suggestions on how to fix this? 
`error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for blis
        Running setup.py clean for blis
      Failed to build thinc preshed blis
      Installing collected packages: wrapt, wasabi, srsly, plac, murmurhash, cymem, wheel, tqdm, six, setuptools, preshed, numpy, Cython, thinc_gpu_ops, blis, thinc
        Running setup.py install for preshed: started
        Running setup.py install for preshed: finished with status 'error'
        error: subprocess-exited-with-error
      
        × Running setup.py install for preshed did not run successfully.
        │ exit code: 1
        ╰─> [14 lines of output]
            /home/sdspieg/.env/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
              warnings.warn(
            running install
            /home/sdspieg/.env/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
              warnings.warn(
            running build
            running build_py
            running build_ext
            building 'preshed.maps' extension
            x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/include/python3.10 -I/home/sdspieg/.env/include -I/usr/include/python3.10 -c preshed/maps.cpp -o build/temp.linux-x86_64-cpython-310/preshed/maps.o -O3 -Wno-strict-prototypes -Wno-unused-function
            cc1plus: warning: command-line option ‘-Wno-strict-prototypes’ is valid for C/ObjC but not for C++
            cc1plus: fatal error: preshed/maps.cpp: No such file or directory
            compilation terminated.
            error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: legacy-install-failure
      
      × Encountered error while trying to install package.
      ╰─> preshed
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for output from the failure.
      [end of output]
  
`

**Comment by sdspieg** [comment]
UPD - the problem seems to be with spaCy 2.1 (and blis, presumably).

**Comment by sdspieg** [comment]
UPD - tried in Windows (and yes, after installing MSVC 14.0) and also wasn't able to make it work

`PS C:\Users\sdspi\Documents> pip install holmes-extractor
Collecting holmes-extractor
  Using cached holmes_extractor-3.0.0-py3-none-any.whl (112 kB)
Collecting coreferee~=1.1.0
  Using cached coreferee-1.1.3-py3-none-any.whl (187 kB)
Collecting spacy<3.2.0,>=3.1.0
  Using cached spacy-3.1.6-cp310-cp310-win_amd64.whl (11.2 MB)
Collecting sklearn
  Using cached sklearn-0.0.tar.gz (1.1 kB)
  Preparing metadata (setup.py) ... done
Collecting jsonpickle
  Using cached jsonpickle-2.1.0-py2.py3-none-any.whl (38 kB)
Collecting bs4
  Using cached bs4-0.0.1.tar.gz (1.1 kB)
  Preparing metadata (setup.py) ... done
Collecting scipy
  Using cached scipy-1.8.0-cp310-cp310-win_amd64.whl (37.0 MB)
Collecting falcon
  Using cached falcon-3.1.0-cp310-cp310-win_amd64.whl (1.7 MB)
Collecting rdflib
  Using cached rdflib-6.1.1-py3-none-any.whl (482 kB)
Collecting msgpack-numpy
  Using cached msgpack_numpy-0.4.7.1-py2.py3-none-any.whl (6.7 kB)
Collecting torch
  Using cached torch-1.11.0-cp310-cp310-win_amd64.whl (158.0 MB)
Collecting coreferee~=1.1.0
  Using cached coreferee-1.1.2-py3-none-any.whl (179 kB)
  Using cached coreferee-1.1.1-py3-none-any.whl (149 kB)
  Using cached coreferee-1.1.0-py3-none-any.whl (152 kB)
Collecting keras~=2.4.0
  Using cached Keras-2.4.3-py2.py3-none-any.whl (36 kB)
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of holmes-extractor to determine which version is compatible with other requirements. This could take a while.
Collecting holmes-extractor
  Using cached holmes-extractor-2.2.1.tar.gz (115 kB)
  Preparing metadata (setup.py) ... done
Collecting spacy==2.1.0
  Using cached spacy-2.1.0.tar.gz (27.7 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [140 lines of output]
      Collecting setuptools
        Using cached setuptools-62.1.0-py3-none-any.whl (1.1 MB)
      Collecting wheel>0.32.0.<0.33.0
        Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting Cython
        Using cached Cython-0.29.28-py2.py3-none-any.whl (983 kB)
      Collecting cymem<2.1.0,>=2.0.2
        Using cached cymem-2.0.6-cp310-cp310-win_amd64.whl (36 kB)
      Collecting preshed<2.1.0,>=2.0.1
        Using cached preshed-2.0.1.tar.gz (113 kB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): still running...
        Preparing metadata (setup.py): finished with status 'done'
      Collecting murmurhash<1.1.0,>=0.28.0
        Using cached murmurhash-1.0.7-cp310-cp310-win_amd64.whl (18 kB)
      Collecting thinc==7.0.0.dev6
        Using cached thinc-7.0.0.dev6.tar.gz (1.9 MB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): still running...
        Preparing metadata (setup.py): finished with status 'done'
      Collecting blis<0.3.0,>=0.2.1
        Using cached blis-0.2.4.tar.gz (1.5 MB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): still running...
        Preparing metadata (setup.py): finished with status 'done'
      Collecting thinc_gpu_ops<0.1.0,>=0.0.1
        Using cached thinc_gpu_ops-0.0.4.tar.gz (483 kB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): still running...
        Preparing metadata (setup.py): finished with status 'done'
      Collecting numpy>=1.7.0
        Using cached numpy-1.22.3-cp310-cp310-win_amd64.whl (14.7 MB)
      Collecting wrapt<1.11.0,>=1.10.0
        Using cached wrapt-1.10.11.tar.gz (27 kB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): still running...
        Preparing metadata (setup.py): finished with status 'done'
      Collecting plac<1.0.0,>=0.9.6
        Using cached plac-0.9.6-py2.py3-none-any.whl (20 kB)
      Collecting tqdm<5.0.0,>=4.10.0
        Using cached tqdm-4.64.0-py2.py3-none-any.whl (78 kB)
      Collecting six<2.0.0,>=1.10.0
        Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
      Collecting wasabi<1.1.0,>=0.0.9
        Using cached wasabi-0.9.1-py3-none-any.whl (26 kB)
      Collecting srsly<1.1.0,>=0.0.5
        Using cached srsly-1.0.5.tar.gz (86 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: still running...
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: still running...
        Installing backend dependencies: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting colorama
        Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
      Using legacy 'setup.py install' for thinc, since package 'wheel' is not installed.
      Using legacy 'setup.py install' for preshed, since package 'wheel' is not installed.
      Using legacy 'setup.py install' for blis, since package 'wheel' is not installed.
      Using legacy 'setup.py install' for thinc_gpu_ops, since package 'wheel' is not installed.
      Using legacy 'setup.py install' for wrapt, since package 'wheel' is not installed.
      Building wheels for collected packages: srsly
        Building wheel for srsly (pyproject.toml): started
        Building wheel for srsly (pyproject.toml): still running...
        Building wheel for srsly (pyproject.toml): finished with status 'done'
        Created wheel for srsly: filename=srsly-1.0.5-cp310-cp310-win_amd64.whl size=168872 sha256=d751c0b2ea2ca9bc2c209bfb0310d5956e363ee115b220d4cadd9684e974086b
        Stored in directory: c:\users\sdspi\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local\pip\cache\wheels\6c\d4\c1\459f2fe59bfecd479ac8149afb766940421b6504fad684743b
      Successfully built srsly
      Installing collected packages: wrapt, wasabi, srsly, plac, murmurhash, cymem, wheel, six, setuptools, preshed, numpy, Cython, colorama, tqdm, thinc_gpu_ops, blis, thinc
        Running setup.py install for wrapt: started
        Running setup.py install for wrapt: still running...
        Running setup.py install for wrapt: finished with status 'done'
        Running setup.py install for preshed: started
        Running setup.py install for preshed: still running...
        Running setup.py install for preshed: finished with status 'error'
        error: subprocess-exited-with-error

        Running setup.py install for preshed did not run successfully.
        exit code: 1

        [44 lines of output]
        WARNING: The wheel package is not available.
        running install
        running build
        running build_py
        creating build
        creating build\lib.win-amd64-3.10
        creating build\lib.win-amd64-3.10\preshed
        copying preshed\about.py -> build\lib.win-amd64-3.10\preshed
        copying preshed\__init__.py -> build\lib.win-amd64-3.10\preshed
        creating build\lib.win-amd64-3.10\preshed\tests
        copying preshed\tests\test_counter.py -> build\lib.win-amd64-3.10\preshed\tests
        copying preshed\tests\test_hashing.py -> build\lib.win-amd64-3.10\preshed\tests
        copying preshed\tests\test_pop.py -> build\lib.win-amd64-3.10\preshed\tests
        copying preshed\tests\__init__.py -> build\lib.win-amd64-3.10\preshed\tests
        copying preshed\counter.pyx -> build\lib.win-amd64-3.10\preshed
        copying preshed\maps.pyx -> build\lib.win-amd64-3.10\preshed
        copying preshed\counter.pxd -> build\lib.win-amd64-3.10\preshed
        copying preshed\maps.pxd -> build\lib.win-amd64-3.10\preshed
        copying preshed\__init__.pxd -> build\lib.win-amd64-3.10\preshed
        running build_ext
        building 'preshed.maps' extension
        creating build\temp.win-amd64-3.10
        creating build\temp.win-amd64-3.10\Release
        creating build\temp.win-amd64-3.10\Release\preshed
        C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.31.31103\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\include -IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\include -IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\Include -IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.31.31103\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.2\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt /EHsc /Tppreshed/maps.cpp /Fobuild\temp.win-amd64-3.10\Release\preshed/maps.obj /Ox /EHsc
        maps.cpp
        preshed/maps.cpp(5728): error C2039: 'tp_print': is not a member of '_typeobject'
        C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\include\cpython/object.h(191): note: see declaration of '_typeobject'
        preshed/maps.cpp(5740): error C2039: 'tp_print': is not a member of '_typeobject'
        C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\include\cpython/object.h(191): note: see declaration of '_typeobject'
        preshed/maps.cpp(5749): error C2039: 'tp_print': is not a member of '_typeobject'
        C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\include\cpython/object.h(191): note: see declaration of '_typeobject'
        preshed/maps.cpp(5755): error C2039: 'tp_print': is not a member of '_typeobject'
        C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\include\cpython/object.h(191): note: see declaration of '_typeobject'
        preshed/maps.cpp(5761): error C2039: 'tp_print': is not a member of '_typeobject'
        C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\include\cpython/object.h(191): note: see declaration of '_typeobject'
        preshed/maps.cpp(5767): error C2039: 'tp_print': is not a member of '_typeobject'
        C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\include\cpython/object.h(191): note: see declaration of '_typeobject'
        preshed/maps.cpp(6129): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
        preshed/maps.cpp(6145): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
        preshed/maps.cpp(8447): error C3861: '_PyGen_Send': identifier not found
        preshed/maps.cpp(8452): error C3861: '_PyGen_Send': identifier not found
        preshed/maps.cpp(8536): error C3861: '_PyGen_Send': identifier not found
        error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.31.31103\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: legacy-install-failure

      Encountered error while trying to install package.

      preshed

      note: This is an issue with the package mentioned above, not pip.
      hint: See above for output from the failure.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

**Comment by richardpaulhudson** [comment]
Please try again with the new version Holmes 4.0.0, make sure you start with a completely fresh virtual Python environment (see https://docs.python.org/3/library/venv.html) and follow the instructions in the Holmes introduction exactly. The fact that spaCy 2.1 is involved suggests libraries may have been installed other than as part of the Holmes installation.
